CREATE TABLE [dbo].[Table] (
    [USERNAME] VARCHAR (50) NOT NULL,
    [PASSWORD] VARCHAR (50) NOT NULL,
    [NAME] VARCHAR(50) NOT NULL, 
    [IDNO] VARCHAR(50) NOT NULL, 
    [PROFESSION] VARCHAR(50) NOT NULL, 
    [MOBILENO] VARCHAR(50) NOT NULL, 
    PRIMARY KEY CLUSTERED ([USERNAME] ASC)
);

