CREATE TABLE [dbo].[Table]
(
	[USERNAME] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [PASSWORD] VARCHAR(50) NOT NULL, 
    [NAME] VARCHAR(50) NULL, 
    [IDNO] VARCHAR(50) NULL, 
    [MOBILENO] VARCHAR(50) NULL, 
    [PROFFESIONS] VARCHAR(50) NULL
)
